model_name: efficientad
class_path: anomalib.models.EfficientAd
init_args:
  imagenet_dir: ./efficientad_resources/imagenette
  model_size: small
  lr: 0.0001
  weight_decay: 0.00001
train_batch_size: 1
max_epochs: 100
result_dirname: EfficientAd
normalization: none
